### ISSUE TITLE
Consideration of a detailed guide and a question

### ISSUE THREAD

**Issue by sunnytan53** [andyoneal/DSPMac#1]
I am sorry that I can't really understand the steps of the guide on the Tips. 
Would you mind providing a detailed guide or making a video of how to do so?

Another question I have is: is it possible to make it run with Parallels Desktop?

**Comment by andyoneal** [comment]
Happy to provide better instructions

**Comment by andyoneal** [comment]
Happy to provide better instructions when I get back from vacation, although last time I tried Parallels, the mecha showed up fine and this mod shouldn’t be necessary. Are you not seeing the player mecha in parallels?

**Comment by CiYuan53** [comment]
In fact, I don't even know what and where that is. I think most gamers don't know about virtual machine stuff. It will be appreciated if you can provide some simple instructions like which tab and setting to look for to change, etc.

**Comment by sunnytan53** [comment]
I think I may misread/misunderstand some parts. But thank you for replying!

**Comment by andyoneal** [comment]
@CiYuan53 I've added an install guide.
